version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: counter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - counter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: counter-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DEBUG=false
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - counter-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  counter-network:
    driver: bridge